// Variants are also persisted in variants.json. Inlined here so the prototype
// works without a fetch (file:// safe). Keep these in sync.
window.NUANU_VARIANTS = {
  master: {
    id: "master",
    audience: "Healthspan",
    audienceNote: "High-net-worth 45–60, optimising biological age.",
    h1: "Reverse your biological age in fourteen days, and prove it.",
    sub: "A clinical longevity programme at Nuanu Creative City, Bali. Sixty-marker panel, DunedinPACE epigenetic age, VO2max, continuous glucose. Diagnose, practice, restore — and leave with data you can act on.",
    trustStrip: ["Application only", "Cohort of 10", "Bali · October 2026"],
    hook: "60-marker panel · DunedinPACE · VO2max",
    priceBand: "$9,800 — $13,500",
    heroAlt: "Dawn light on a terrace at Nuanu Creative City. A single fifty-five-year-old man in linen walks away from the camera toward a palm-shaded path. Wide angle, depth, no other figures.",
    heroCaption: "hero · dawn · terrace · figure walking · palm path",
    heroPalette: ["#2c382c", "#5b6049", "#a18960", "#dec19a"],
    heroImage: "/images/hero-healthspan.png",
  },
  unplug: {
    id: "unplug",
    audience: "Unplug",
    audienceNote: "Burnout reset for senior operators.",
    h1: "Fourteen days off your nervous system.",
    sub: "A clinical longevity programme at Nuanu Creative City, Bali. Phone-free protocol, continuous HRV, sleep architecture, breath and sound work. Diagnose, practice, restore — and leave with a nervous system you recognise again.",
    trustStrip: ["Application only", "Cohort of 10", "Bali · October 2026"],
    hook: "WHOOP · phone-free protocol",
    priceBand: "$9,800 — $13,500",
    heroAlt: "A woman in her late forties, head tipped back into the deep shade of a daybed, eyes closed. The ocean is a soft horizon line beyond. Mid-afternoon, natural light, candid.",
    heroCaption: "hero · daybed · ocean horizon · head back · shade",
    heroPalette: ["#1f2a30", "#3f5a64", "#7a98a0", "#d3d2c5"],
    heroImage: "/images/hero-unplug.png",
  },
  reset: {
    id: "reset",
    audience: "Reset",
    audienceNote: "Metabolic reset and weight.",
    h1: "See what your body has been hiding.",
    sub: "A clinical longevity programme at Nuanu Creative City, Bali. Continuous glucose monitoring, sixty-marker blood panel, nutrition coaching, daily movement. Diagnose, practice, restore — and leave knowing exactly what your meals are doing.",
    trustStrip: ["Application only", "Cohort of 10", "Bali · October 2026"],
    hook: "Continuous glucose monitor, take-home",
    priceBand: "$9,800 — $13,500",
    heroAlt: "Close-up of a continuous glucose monitor on the upper arm of a person standing at a kitchen counter, morning light from a side window. A ceramic cup and a knife on a wooden board sit just out of focus.",
    heroCaption: "hero · CGM upper arm · kitchen · morning light",
    heroPalette: ["#2e2620", "#6a513c", "#b48b62", "#ecd5b1"],
    heroImage: "/images/hero-reset.png",
  },
  moms_reset: {
    id: "moms_reset",
    audience: "Mom's Reset",
    audienceNote: "Gifted to a parent by an adult child.",
    h1: "Give your mother fourteen days she would never give herself.",
    sub: "A clinical longevity programme at Nuanu Creative City, Bali. Full medical workup, gentle daily practice, doctor-supervised rest. Diagnose, practice, restore — and a daily WhatsApp update so you know she is well.",
    trustStrip: ["Application only", "Cohort of 10", "Bali · October 2026"],
    hook: "Daily WhatsApp updates to you",
    priceBand: "$9,800 — $13,500",
    heroAlt: "Two pairs of hands, one older and one younger, holding small ceramic tea cups across a worn wooden table. Late-morning side light. Faces out of frame. Candid.",
    heroCaption: "hero · two hands · tea cups · wooden table · side light",
    heroPalette: ["#2a1f17", "#6f4f33", "#b0875a", "#e6ceaa"],
    heroImage: "/images/hero-moms.png",
  },
  work_well: {
    id: "work_well",
    audience: "Work Well",
    audienceNote: "A 14-day workation with diagnostics.",
    h1: "Work from Bali. Leave with a VO2 score.",
    sub: "A clinical longevity programme at Nuanu Creative City, Bali. Fibre desks, paddock-quiet calls, full diagnostics around your meeting calendar. Diagnose, practice, restore — and ship home with biomarkers, not just photographs.",
    trustStrip: ["Application only", "Cohort of 10", "Bali · October 2026"],
    hook: "The only workation that ships you home with biomarkers",
    priceBand: "$9,800 — $13,500",
    heroAlt: "A laptop and a leather notebook open on a terrace table overlooking a green expanse of rice fields. Two ceramic cups, a pair of glasses, no person. Late-afternoon light.",
    heroCaption: "hero · laptop · notebook · rice fields · no person",
    heroPalette: ["#283224", "#4d6a3f", "#9bb079", "#dfd6b5"],
    heroImage: "/images/hero-workwell.png",
  },

  // ---------------------------------------------------------------------------
  // Wellness retreats — no devices, no resident practitioners, 7 days, $5K flat.
  // ---------------------------------------------------------------------------
  parents: {
    id: "parents",
    kind: "wellness",
    audience: "Parents Vitality",
    audienceNote: "For parents who deserve to be taken care of.",
    tag: "For parents who deserve to be taken care of.",
    h1: "More healthy years together.",
    sub: "Seven days at Nuanu Creative City, Bali, for active adults 50–70. Not a medical programme — a reset for the people who spent their lives taking care of others. Move gently, sleep deeply, eat well, be looked after by a team that knows your parent's name from day one.",
    trustStrip: ["Seven days", "All-inclusive", "Cohort of 10", "From $5,000"],
    hook: "Seven days · The gift that actually lasts",
    priceBand: "$5,000",
    heroAlt: "Two parents in their early sixties walk side by side along a quiet garden path at Nuanu Creative City at dawn. Warm side light, linen clothes, palms in the background. Candid, no posing.",
    heroCaption: "hero · parents at dawn · garden path · warm light",
    heroPalette: ["#2c382c", "#806a52", "#c6a47a", "#ecd9b8"],
    heroImage: "/images/hero-parents.png",

    premise: "Most gifts are forgotten by next week. This one adds years. For seven days your parent steps inside a programme built around gentle movement, deep restoration, real food and unhurried human connection — and comes home different. Looser shoulders. Slower breath. A longer fuse. A clearer head. The kind of difference the people closest to them notice first.",

    outcomes: {
      intro: "After seven days at Nuanu, expect:",
      items: [
        { title: "Sleep that resets",                                    body: "Usually inside the first three nights." },
        { title: "Looser hips, looser shoulders, better balance",        body: "Often noticeable by day five." },
        { title: "A nervous system that has stopped running ahead",      body: "Calmer mornings, a longer fuse." },
        { title: "Habits that survive the flight home",                   body: "Five minutes of mobility, ten minutes of breath, a walking pace they enjoy." },
        { title: "A take-home book of recipes, playlists and routines",   body: "Designed for their kitchen, not ours." },
      ],
      forIntro: "This retreat is for parents 50–70 who are:",
      forItems: [
        "Still active, still curious.",
        "Comfortable on a twenty-minute walk (everything else scales).",
        "Quietly tired of being the one who takes care of everyone else.",
        "The kind of person who would never book this for themselves.",
      ],
    },

    midCta: {
      eyebrow: "Seven days · all-inclusive · from $5,000",
      headline: "A small cohort, a quiet week, a gift that lasts.",
      buttonLabel: "Request an invitation",
    },

    day: {
      heading: "A day at Nuanu",
      intro: "Days flex. The body, not the clock, sets the pace. One illustrative shape, held gently.",
      moments: [
        { time: "06:30", title: "Wake gently",            body: "Tea on the verandah, a slow walk on the beach as the light comes up.",                   palette: ["#1f2218","#3c4530","#7a8265","#c7c5a8"], cap: "06:30 · verandah · sunrise · tea pot",                 image: null },
        { time: "08:00", title: "Mobility & breath",       body: "Open-air deck, coach-led, never more than ten on the mat.",                              palette: ["#1d2b29","#2f4a44","#6e8a82","#c3d0c8"], cap: "08:00 · open-air movement deck · jungle behind",       image: "/images/pillar-move.png" },
        { time: "09:00", title: "Slow breakfast",          body: "Garden seating, table-style, no rush.",                                                   palette: ["#241a13","#5a3f2a","#a78057","#e5cba2"], cap: "09:00 · garden breakfast · plates and bowls",          image: null },
        { time: "10:30", title: "Free",                    body: "Lumeira spa, sound dome, or the pool — your parent's call, not yours.",                  palette: ["#22180f","#4d3621","#9a754c","#e3c89b"], cap: "10:30 · spa pavilion · linen drapes · soft light",     image: "/images/pillar-rest.png" },
        { time: "12:30", title: "Long lunch",              body: "Plant-forward, Mediterranean-Bali plating, served at the cohort table.",                 palette: ["#2a1f17","#6f4f33","#b08461","#ecd0a8"], cap: "12:30 · long lunch table · shared dishes",             image: null },
        { time: "14:00", title: "Villa massage",           body: "Or quiet rest. By day three, the body asks for one of these without being prompted.",    palette: ["#1e2a30","#3a5764","#7d9aa5","#d2dadd"], cap: "14:00 · massage table · folded linen · candle",        image: "/images/pillar-restore.png" },
        { time: "16:00", title: "Strength & posture",       body: "Gentle, group of ten, focused on balance and ease — the things that matter at sixty.",  palette: ["#1f2a18","#3a4b2c","#7a8c5a","#c8d1aa"], cap: "16:00 · pavilion · standing balance work",             image: null },
        { time: "17:30", title: "Sunset meditation",        body: "On the deck, facing the ocean. Twenty minutes that recalibrate the week.",              palette: ["#2a1f17","#6f4f33","#b0875a","#e6ceaa"], cap: "17:30 · sunset deck · facing the ocean",               image: null },
        { time: "19:00", title: "Dinner together",          body: "Cohort table, shared dishes, candles, no phones.",                                       palette: ["#1d2b29","#2f4a44","#6e8a82","#c3d0c8"], cap: "19:00 · cohort dinner · blue hour · candles",          image: "/images/pillar-connect.png" },
        { time: "20:30", title: "Sound healing",            body: "Or a quiet read by the pool. Bed early — by day four, that is the request, not the rule.", palette: ["#22180f","#4d3621","#9a754c","#e3c89b"], cap: "20:30 · sound bowls · low light · spa floor",           image: null },
      ],
    },

    whyNuanu: {
      heading: "Why Nuanu",
      intro: "Nuanu Creative City is a 44-hectare campus on Bali's west coast — wellness pavilions, jungle trails, dunes and sunset beach in one walkable village. A non-clinical setting, on purpose. No machines, no devices, no white walls. A retreat, not a clinic.",
      points: [
        { title: "Lumeira Wellness",                            body: "A full spa pavilion: massage, hydrotherapy, sound dome, ritual treatments. Daily access for every guest." },
        { title: "Open-air movement studios",                    body: "Teak decks for mobility, yoga, posture and balance work — shaded, unhurried, never crowded." },
        { title: "Bali-grown, Mediterranean-inspired food",       body: "Three meals a day, plant-forward, every dietary need quietly handled. Served table-style." },
        { title: "Private single-storey villas",                  body: "Step-free where it matters, quiet at night, with a verandah for the morning tea ritual." },
        { title: "A cohort of ten, never more",                  body: "By day two, the guides, therapists and host team know every guest by name." },
        { title: "One walkable campus",                           body: "No minibus transfers between activities. Beach, jungle, spa and movement deck are minutes apart." },
      ],
    },

    faq: {
      heading: "Questions",
      intro: "Short answers to what gift-buyers ask us most.",
      items: [
        { q: "Is this medical?",                          a: "No. No diagnostics, no protocols, no resident doctor on call. A wellness retreat designed for active adults." },
        { q: "What if my parent is shy in groups?",        a: "Cohort caps at ten and every activity is opt-in. Many guests arrive on their own and leave with a small circle." },
        { q: "Can two parents come together?",             a: "Yes. Companion pricing is available on request — they share a villa, attend the same programme." },
        { q: "What is the fitness floor?",                  a: "Comfortable walking for twenty minutes. Everything else scales — every class has a gentler option." },
        { q: "Where exactly is Nuanu?",                     a: "Tabanan, on the west coast of Bali — about ninety minutes from Denpasar (DPS) airport. Pickup included." },
        { q: "When do cohorts run?",                         a: "Monthly. Next available dates are shared on application." },
        { q: "Can I get daily updates while they are there?", a: "Yes. A short photo and note from the host team, sent on WhatsApp once a day, on request." },
      ],
    },

    closing: {
      line: "More healthy years together.",
      sub: "Seven days. From $5,000. Cohorts running monthly.",
      buttonLabel: "Request an invitation",
    },


    pillars: [
      {
        title: "Move",
        cadence: "Days 1 — 7",
        body: "Daily guided sessions at human pace. Never more than ten people on the mat.",
        image: "/images/pillar-move.png",
        imageAlt: "A woman in her early sixties, silver hair pulled back, mid-stretch on a woven rattan mat in an open-air teak pavilion at Nuanu Creative City, mid-morning side light, palm canopy beyond.",
        imageCaption: "pillar · move · pavilion · mat · morning light",
        imagePalette: ["#2c382c", "#5b6049", "#a18960", "#dec19a"],
        items: [
          "Mobility classes",
          "Stretching",
          "Joint mobility training",
          "Balance training",
          "Gentle strength training",
          "Walking routines",
          "Breathwork & posture training",
        ],
      },
      {
        title: "Rest",
        cadence: "Throughout",
        body: "Sound healing, breathwork and nervous system regulation. Sleep hygiene built into every day.",
        image: "/images/pillar-rest.png",
        imageAlt: "Three brass Tibetan singing bowls on a folded cream linen cloth, a wooden mallet beside them and a single beeswax candle burning low, frangipani blossom near the largest bowl, polished spa floor.",
        imageCaption: "pillar · rest · singing bowls · candle · spa floor",
        imagePalette: ["#2a1f17", "#6f4f33", "#b0875a", "#e6ceaa"],
        items: [
          "Sound healing",
          "Evening breathwork",
          "Sunset meditation",
          "Sleep hygiene programme",
        ],
      },
      {
        title: "Restore",
        cadence: "Throughout",
        body: "Massage, spa and Nuanu campus activations. Your nervous system reorganises around the slower tempo.",
        image: "/images/pillar-restore.png",
        imageAlt: "Practitioner's hands working a slow stroke down a guest's relaxed forearm on a white-draped massage table at Lumeira spa, a frangipani branch in a stone vessel softly out of focus on the right.",
        imageCaption: "pillar · restore · massage hands · lumeira spa",
        imagePalette: ["#22180f", "#4d3621", "#9a754c", "#e3c89b"],
        items: [
          "Daily villa massage",
          "Lumeira spa rituals",
          "Nuanu campus activations",
        ],
      },
      {
        title: "Connect",
        cadence: "Throughout",
        body: "Group dinners, excursions and evening gatherings. A small cohort, real connection, someone always nearby.",
        image: "/images/pillar-connect.png",
        imageAlt: "A long teak dinner table set for eight at blue hour, plant-forward sharing dishes mid-meal, three lit beeswax candles down the centre, hands at the edges reaching for plates, palm silhouettes against a deep teal sky beyond the pavilion eaves.",
        imageCaption: "pillar · connect · cohort dinner · blue hour",
        imagePalette: ["#1d2b29", "#2f4a44", "#6e8a82", "#c3d0c8"],
        items: [
          "Cohort dinners",
          "Campus excursions",
          "Evening gatherings",
        ],
      },
    ],

    investment: {
      price: "$5,000",
      priceUnit: "per guest · seven days",
      duration: "Seven days, all-inclusive",
      cohort: "Up to 10 guests · application only",
      included: [
        "Seven nights, private villa accommodation",
        "All meals, plant-forward, glucose-aware",
        "Daily guided movement at human pace",
        "Sound healing, breathwork and meditation",
        "Daily villa massage and Lumeira spa rituals",
        "Cohort dinners and campus excursions",
        "Airport transfer from Denpasar (DPS)",
      ],
      notIncluded: [
        "Flights to and from Denpasar (DPS)",
        "Travel insurance",
        "Specialist add-ons",
        "Companion accommodation (available, priced separately)",
        "Gratuities (genuinely optional)",
      ],
    },
  },
};
