// Variants are also persisted in variants.json. Inlined here so the prototype
// works without a fetch (file:// safe). Keep these in sync.
window.NUANU_VARIANTS = {
  master: {
    id: "master",
    audience: "Healthspan",
    audienceNote: "High-net-worth 45–60, optimising biological age.",
    h1: "Reverse your biological age in fourteen days, and prove it.",
    sub: "A clinical longevity programme at Nuanu Creative City, Bali. Sixty-marker panel, DunedinPACE epigenetic age, VO2max, continuous glucose. Diagnose, practice, restore — and leave with data you can act on.",
    trustStrip: ["Application only", "Cohort of 10", "Bali · October 2026"],
    hook: "60-marker panel · DunedinPACE · VO2max",
    priceBand: "$9,800 — $13,500",
    heroAlt: "Dawn light on a terrace at Nuanu Creative City. A single fifty-five-year-old man in linen walks away from the camera toward a palm-shaded path. Wide angle, depth, no other figures.",
    heroCaption: "hero · dawn · terrace · figure walking · palm path",
    heroPalette: ["#2c382c", "#5b6049", "#a18960", "#dec19a"],
    heroImage: "/images/hero-healthspan.png",
  },
  unplug: {
    id: "unplug",
    audience: "Unplug",
    audienceNote: "Burnout reset for senior operators.",
    h1: "Fourteen days off your nervous system.",
    sub: "A clinical longevity programme at Nuanu Creative City, Bali. Phone-free protocol, continuous HRV, sleep architecture, breath and sound work. Diagnose, practice, restore — and leave with a nervous system you recognise again.",
    trustStrip: ["Application only", "Cohort of 10", "Bali · October 2026"],
    hook: "WHOOP · phone-free protocol",
    priceBand: "$9,800 — $13,500",
    heroAlt: "A woman in her late forties, head tipped back into the deep shade of a daybed, eyes closed. The ocean is a soft horizon line beyond. Mid-afternoon, natural light, candid.",
    heroCaption: "hero · daybed · ocean horizon · head back · shade",
    heroPalette: ["#1f2a30", "#3f5a64", "#7a98a0", "#d3d2c5"],
    heroImage: "/images/hero-unplug.png",
  },
  reset: {
    id: "reset",
    audience: "Reset",
    audienceNote: "Metabolic reset and weight.",
    h1: "See what your body has been hiding.",
    sub: "A clinical longevity programme at Nuanu Creative City, Bali. Continuous glucose monitoring, sixty-marker blood panel, nutrition coaching, daily movement. Diagnose, practice, restore — and leave knowing exactly what your meals are doing.",
    trustStrip: ["Application only", "Cohort of 10", "Bali · October 2026"],
    hook: "Continuous glucose monitor, take-home",
    priceBand: "$9,800 — $13,500",
    heroAlt: "Close-up of a continuous glucose monitor on the upper arm of a person standing at a kitchen counter, morning light from a side window. A ceramic cup and a knife on a wooden board sit just out of focus.",
    heroCaption: "hero · CGM upper arm · kitchen · morning light",
    heroPalette: ["#2e2620", "#6a513c", "#b48b62", "#ecd5b1"],
    heroImage: "/images/hero-reset.png",
  },
  moms_reset: {
    id: "moms_reset",
    audience: "Mom's Reset",
    audienceNote: "Gifted to a parent by an adult child.",
    h1: "Give your mother fourteen days she would never give herself.",
    sub: "A clinical longevity programme at Nuanu Creative City, Bali. Full medical workup, gentle daily practice, doctor-supervised rest. Diagnose, practice, restore — and a daily WhatsApp update so you know she is well.",
    trustStrip: ["Application only", "Cohort of 10", "Bali · October 2026"],
    hook: "Daily WhatsApp updates to you",
    priceBand: "$9,800 — $13,500",
    heroAlt: "Two pairs of hands, one older and one younger, holding small ceramic tea cups across a worn wooden table. Late-morning side light. Faces out of frame. Candid.",
    heroCaption: "hero · two hands · tea cups · wooden table · side light",
    heroPalette: ["#2a1f17", "#6f4f33", "#b0875a", "#e6ceaa"],
    heroImage: "/images/hero-moms.png",
  },
  work_well: {
    id: "work_well",
    audience: "Work Well",
    audienceNote: "A 14-day workation with diagnostics.",
    h1: "Work from Bali. Leave with a VO2 score.",
    sub: "A clinical longevity programme at Nuanu Creative City, Bali. Fibre desks, paddock-quiet calls, full diagnostics around your meeting calendar. Diagnose, practice, restore — and ship home with biomarkers, not just photographs.",
    trustStrip: ["Application only", "Cohort of 10", "Bali · October 2026"],
    hook: "The only workation that ships you home with biomarkers",
    priceBand: "$9,800 — $13,500",
    heroAlt: "A laptop and a leather notebook open on a terrace table overlooking a green expanse of rice fields. Two ceramic cups, a pair of glasses, no person. Late-afternoon light.",
    heroCaption: "hero · laptop · notebook · rice fields · no person",
    heroPalette: ["#283224", "#4d6a3f", "#9bb079", "#dfd6b5"],
    heroImage: "/images/hero-workwell.png",
  },
};
